## Jupyter notebook of code to get Lowest Tide Times
- works by getting the troughs from the water_level column
- output is a dataframe

In [1]:
import pandas as pd
# use scipy find_peaks in the negative to find the troughs
from scipy.signal import find_peaks

In [2]:
# get the file html, sourced in ERDDAP
file = 'https://erddap.marine.ie/erddap/tabledap/IMI-TidePrediction.csvp?time%2Clongitude%2Clatitude%2CstationID%2CWater_Level%2CWater_Level_ODM&time%3E=2023-01-01&time%3C=2024-01-01'

df = pd.read_csv(file)

In [3]:
# use the negative to find the troughs
# this returns a tuple
troughs = find_peaks(-(df['Water_Level (metres)']))

In [4]:
# the first index of the tuple has a list of indices
troughlist = troughs[0]

In [5]:
# use take() to get the rows from the list of indices above
troughcheckdf = df.take(troughlist)
troughcheckdf

,time (UTC),longitude (degrees_east),latitude (degrees_north),stationID,Water_Level (metres),Water_Level_ODM (metres)
80,2023-01-01T06:55:00Z,-10.1016,53.9522,Achill_Island_MODELLED,1.51,-0.92
231,2023-01-01T19:30:00Z,-10.1016,53.9522,Achill_Island_MODELLED,1.20,-1.23
382,2023-01-02T08:05:00Z,-10.1016,53.9522,Achill_Island_MODELLED,1.47,-0.96
532,2023-01-02T20:35:00Z,-10.1016,53.9522,Achill_Island_MODELLED,1.26,-1.17
683,2023-01-03T09:10:00Z,-10.1016,53.9522,Achill_Island_MODELLED,1.37,-1.06
...,...,...,...,...,...,...
3888810,2023-12-29T18:55:00Z,-6.0127,52.9889,Wicklow_MODELLED,0.65,-0.96
3888953,2023-12-30T06:50:00Z,-6.0127,52.9889,Wicklow_MODELLED,0.88,-0.73
3889107,2023-12-30T19:40:00Z,-6.0127,52.9889,Wicklow_MODELLED,0.74,-0.87
3889248,2023-12-31T07:25:00Z,-6.0127,52.9889,Wicklow_MODELLED,0.96,-0.65
3889403,2023-12-31T20:20:00Z,-6.0127,52.9889,Wicklow_MODELLED,0.83,-0.78